page-layout: article

project:
  type: website

format:
  html:
    toc: true
    toc-depth: 5
    toc-location: right
    lightbox: true
    theme: [sandstone, theme.scss]
    css: styles.css
    self-contained: true
    link-external-newwindow: true
    link-external-icon: false
    backgroundcolor: "#f2f6f9"

knitr: 
  opts_chunk: 
    comment: "#>"
    fig.align: "center"
    fig.show: "hold"
    fig.asp: 0.618
    fig.retna: 3
    fig.path: images/
    out.width: 80%

execute:
  freeze: false
  warning: false

website:
  title: "Leah Kaplan"
  description: >
    Personal website for Leah Kaplan.
  favicon: figs/favicon.ico
  back-to-top-navigation: true
  search:
    location: navbar
    type: textbox
    copy-button: true
  navbar:
    left:
      - icon: person-badge
        href: about.qmd
        text: "About"
      - icon: file-bar-graph
        href: research.qmd
        text: "Research"     
      - icon: file-text
        href: blog.qmd
        text: "Blog"
      - icon: person-circle
        href: CV.pdf
        text: "CV"
    right:
      - icon: linkedin
        href: www.linkedin.com/in/leah-kaplan
      - icon: twitter
        href: https://twitter.com/kap_leah
      - icon: github
        href: https://github.com/lkaplan25
      - icon: envelope-at
        href: mailto:lkaplan25@gmail.com
