---
title: "About Me"
---

I am an Associate in [Exponent's Vehicle Engieering Practice](https://www.exponent.com/expertise/vehicle-engineering), specializing in advanced driver assistance systems (ADAS) and autonomous vehicles.

I hold a doctorate in Systems Engineering from the George Washington University, where I was a National Science Foundation Graduate Research Fellow and a fellow with GWU's [Co-Design of Trustworthy AI Systems NSF Research Traineeship Program](https://dtais.seas.gwu.edu/). My dissertation research examined several potential impacts of autonomous vehicles and used them as a case study of the potential societal effects of AI-enabled automation in the physical world.

Prior to starting my PhD, I worked as a program specialist with the [ASU Consortium for Science, Policy & Outcomes (CSPO)](https://cspo.org/) in Washington, DC. My primary focus was supporting CSPO's work on Participatory Technology Assessment (pTA), aiming to incorporate public values and perspectives into critical science and technology decisions. In that role, I helped to coordinate the Consortium’s project “Our Driverless Futures”, involving large-scale public deliberations across the United States, Europe, and Asia on the future of driverless mobility.

My interests in transportation extend beyond my work. I am an avid cyclist and public transit enthusiast. When not at my desk doing research, I'm typically found hiking, boxing, or dancing (my favorite is country swing).

Learn more about how I think about AVs and the future of transportation in the video below:

<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/727232863?h=ca6c6e8403&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="PIT in Action.mp4"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>

<br><br>


::: {style="display: grid; grid-template-columns: 40% 50%; grid-column-gap: 30px; line-height: 1.5rem;"}
<div>

[Research Interests]{.columnname}

-   **Autonomous vehicles**: Exploring the potential impacts of AVs with a focus on labor, cost, and adoption.

-   **Trustworthy artificial intelligence (AI)**: Collaborating on research at the intersection of AI and human work systems. Evaluating different dimensions of trustworthiness.

-   **Transportation equity**: Developing transportation systems that improve transportation access for individuals that are least served by current transportation systems.

-   **Deliberative democracy**: Developing methods for engaging the public in science and technology development and decision-making.

</div>

<div>

[Education]{.columnname}

<ul>

-   PhD in Systems Engineering, The George Washington University

-   B.S. in Chemical Engineering, The University of Arizona

</ul>

</div>
:::
